config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: %i[show index]
  root to: 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products, dependent: :destroy
  has_many :products, through: :category_products
  has_many :subcategories, class_name: 'Category', foreign_key: :parent_id

  belongs_to :parent, class_name: 'Category', optional: true

  PRODUCTS_PER_PAGE = 40

  scope :top_level, -> { where(parent_id: nil) }

  def ancestors
    ancestors = []
    current_parent = parent
    while current_parent
      ancestors.unshift(current_parent)
      current_parent = current_parent.parent
    end
    ancestors
  end

  def products?
    products.any?
  end
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :product
  belongs_to :category

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :category_products, dependent: :destroy
  has_many :categories, through: :category_products

  scope :ordered_by_price_up, -> { order(price: :desc) }
  scope :ordered_by_price_down, -> { order(:price) }
  scope :by_category, ->(category) { where(id: CategoryProduct.where(category_id: category.id).pluck(:id)) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  PRODUCTS_PER_PAGE = 40

  def show
    @category = Category.find(params[:id])
    @products = Product.by_category(@category)
    @pages_count = (@products.count / PRODUCTS_PER_PAGE.to_f).ceil.to_i
    @current_page = params[:page] ? params[:page].to_i : 1
    @order_type = params[:order]
   if params[:page] && params[:order]
      case params[:order]
      when 'expensive'
        @products = @products.ordered_by_price_up
      when 'cheap'
        @products = @products.ordered_by_price_down
      end
     @products = @products.limit(PRODUCTS_PER_PAGE).offset(params[:page].to_i * PRODUCTS_PER_PAGE)
   elsif params[:page]
     @products = @products.limit(PRODUCTS_PER_PAGE).offset(params[:page].to_i * PRODUCTS_PER_PAGE)
   elsif  params[:order]
     case params[:order]
     when 'expensive'
       @products = @products.ordered_by_price_up
     when 'cheap'
       @products = @products.ordered_by_price_down
     end
     @products = @products.limit(PRODUCTS_PER_PAGE).offset(0)
   else
     @products = @products.limit(PRODUCTS_PER_PAGE).offset(0)
   end
  end

  def index
    @categories = Category.top_level
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_navbar.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= categories_path %>">Категории</a></li>
    <% @category.ancestors.each do |ancestor| %>
      <li class="breadcrumb-item"><a href="<%= category_path(ancestor) %>"><%= ancestor.name %></a></li>
    <% end %>
    <li class="breadcrumb-item active" aria-current="page"><%= @category.name %></li>
  </ol>
</nav>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <hr>
      <h2 class="text-center">Категории</h2>
      <hr>
      <div class="row">
        <% @categories.each_with_index do |category,index| %>
          <div class="col-sm-12 col-lg-4">
            <div class="text-center">
              <div class="card-group">
                <div class="card" style="height: 6rem">
                  <div class="card-body">
                    <a href="<%= category_path(category) %>" class="card-link">
                      <h5 class="align-middle"><%= category.name %></h5>
                    </a>
                  </div>
                </div>
              </div>
          <% if (index.next % 1).zero? %>
            <div class="col-md-12">
              <br>
            </div>
          <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <%= render 'categories/navbar' %>
  <div class="row">
    <div class="col-md-2">
      <% if @category.products? %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Сортировать
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="<%= category_path(@category) + "?order=expensive" %>">Дорогие</a>
            <a class="dropdown-item" href="<%=category_path(@category) + "?order=cheap"%>">Дешевые</a>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-10">
      <% if @category.products? %>
        <div class="row">
          <% @products.each_with_index do |product, index| %>
            <div class="col-md-4">
              <div class="card-group">
                <div class="card">
                  <img src="<%= product.image %>" class="img mx-auto " alt="..." height="300px" width="160px">
                  <div class="card-body">
                    <h5 class="text-center" style="height: 7rem"><%= product.title %></h5>
                    <h3 class="text-center"><%= product.price %></h3>
                    <ul>
                      <% p = product.description.split(';')%>
                       <% if p.size > 6 %>
                          <% p.values_at(0,1,5,6).each do |bullet| %>
                            <li class="card-text"><%= bullet %></li>
                          <% end %>
                        <% else %>
                          <% p.first(4).each do |bullet| %>
                            <li class="card-text"><%= bullet %></li>
                          <% end %>
                      <% end %>
                    </ul>
                    <a href="<%= product.url %>" class="btn btn-primary mx-auto">Go to site</a>
                   </div>
                </div>
              </div>
            </div>
              <% if (index.next % 3).zero? %>
                <div class="col-md-12">
                  <hr>
                </div>
              <% end %>
          <% end %>
        </div>
      <% else %>
        <ul class="list-group">
          <% @category.subcategories.each do |subcategory| %>
            <li class="list-group-item text-center">
              <%= link_to subcategory.name, category_path(subcategory) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="col-md-2"></div>
  </div>
  <% if @category.products? %>
    <hr>
    <div class="row justify-content-center align-items-center">
      <% if @pages_count > 1 %>
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item"><a class="page-link" href="<%= category_path(@category) + "?page=1" + (@order_type ? "&order=#{@order_type}" : "") %>">First page</a></li>
            <li class="page-item"><a class="page-link" href="<%= category_path(@category) + "?page=#{@current_page - 1}" + (@order_type ? "&order=#{@order_type}" : "") %>">Previous page</a></li>
            <% (@current_page...( @current_page + 10 > @pages_count ? @pages_count : @current_page + 10 )).each do |page_number|  %>
              <li class="page-item">
                <a class="page-link" href="<%= category_path(@category) + "?page=#{page_number}" + (@order_type ? "&order=#{@order_type}" : "") %>"><%= page_number %></a>
              </li>
            <% end %>
            <li class="page-item"><a class="page-link" href="<%= category_path(@category) + "?page=#{@current_page + 1}" + (@order_type ? "&order=#{@order_type}" : "") %>">Next</a></li>
            <li class="page-item"><a class="page-link" href="<%= category_path(@category) + "?page=#{@pages_count - 1}" + (@order_type ? "&order=#{@order_type}" : "") %>">Last page</a></li>
          </ul>
        </nav>
      <% end %>
    </div>
    <hr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebParserApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>